<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Authors>queil</Authors>
    <Description>Common hashing logic</Description>
    <Copyright>2025 - 2026 © queil</Copyright>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <RepositoryUrl>https://github.com/queil/fsc-host</RepositoryUrl>
    <FsDocsSourceRepository>https://github.com/queil/fsc-host/tree/main</FsDocsSourceRepository>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <IncludeSymbols>true</IncludeSymbols>
    <PackageLicenseExpression>Unlicense</PackageLicenseExpression>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>NU1608</NoWarn>
    <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
    <DisableImplicitLibraryPacksFolder>true</DisableImplicitLibraryPacksFolder>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Hash.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="FSharp.Core" Version="10.1.203" />
  </ItemGroup>


</Project>
