<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>NU1608</NoWarn>
    <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
    <DisableImplicitLibraryPacksFolder>true</DisableImplicitLibraryPacksFolder>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Queil.FSharp.Hashing\Queil.FSharp.Hashing.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Paket.Core" Version="10.3.1" />
    <PackageReference Update="FSharp.Core" Version="10.1.204" />
    <PackageReference Include="NuGet.Packaging" Version="5.11.7" />
  </ItemGroup>


  <ItemGroup>
    <Compile Include="Rids.fs" />
    <Compile Include="PaketDependencyManager.fs" />
  </ItemGroup>

</Project>
